```{r}
library(dplyr)
library(Seurat)
library(patchwork)
library(SeuratDisk)
library(sctransform)
library(ggplot2)
library(harmony)
library(ArchR)
library(ggsci)
```

```{r}
cor <- readRDS("./RNA_clustered_postContamination.rds")
```

```{r}
DimPlot(cor, reduction = 'rna.umap', group.by = 'SCT_snn_res.0.2', label.size = 4, label=TRUE)
```

```{r}
cor = FindMultiModalNeighbors(
  object = cor,
  reduction.list = list("pca", "apca"),
  weighted.nn.name = "sct.dsb_wnn", 
  knn.graph.name = "sct.dsb_knn",
  modality.weight.name = "sct.dsb_weight",
  snn.graph.name = "sct.dsb_snn",
  dims.list = list(1:80, 1:30), 
  verbose = TRUE
)
```

```{r}
cor <- RunUMAP(cor, nn.name = "sct.dsb_wnn", reduction.name = "sct.dsb_wnn_umap", 
            reduction.key = "sct.dsb_wnnUMAP_", verbose = TRUE, return.model = TRUE)
sample <- FindClusters(sample, graph.name = "sct.dsb_snn", algorithm = 3, 
            resolution = c(0.1, 0.2, 0.3, 0.4, 0.5), verbose = TRUE)
```

```{r}
DimPlot(cor, reduction = 'rna.umap', group.by = 'SCT_snn_res.0.2',label.size = 4, label = TRUE)
DimPlot(cor, reduction = 'adt.umap', group.by = 'SCT_snn_res.0.2',label.size = 4, label = TRUE)
DimPlot(cor, reduction = 'sct.dsb_wnn_umap', group.by = 'SCT_snn_res.0.2',label.size = 4, label = TRUE)
```

# Anntotate the Global Clusters
```{r}
fun <- function(x) {
  if (x == "0") {"TCells"} 
  else if (x == "1") {"Myeloid"}
  else if (x == "2") {"SMCPericyte"}
  else if (x == "3") {"Endothelium"}
  else if (x == "4") {"TCells"}
  else if (x == "5") {"Fibroblast1"}
  else if (x == "6") {"BCells"}
  else if (x == "7") {"Fibroblast2"}
  else if (x == "8") {"TCells"}
  else if (x == "9") {"ModSMC"}
  else if (x == "10") {"Mast"}
  else if (x == "11") {"Glia"}
  else if (x == "12") {"Lymphatic"}
  else if (x == "13") {"PlasmaCells"}
  else if (x == "14") {"Proliferating"}
  else if (x == "15") {"pDC"}
  else if (x == "16") {"Myeloid"}
}
cor$cell.type <- mapply(fun, cor$SCT_snn_res.0.2)

cor$cell.type <- factor(cor$cell.type, levels = c("SMCPericyte", "ModSMC", "Fibroblast1", "Fibroblast2", "Endothelium", "Myeloid", "pDC", "Mast", "BCells", "PlasmaCells", "TCells", "Proliferating", "Lymphatic", "Glia"))
```

```{r}
DimPlot(cor, reduction = 'rna.umap', group.by = 'cell.type',label.size = 4,
        cols = paletteDiscrete(unique(cor$cell.type), set = "stallion"), label = FALSE)

DimPlot(cor, reduction = 'adt.umap', group.by = 'cell.type',label.size = 4,
        cols = paletteDiscrete(unique(cor$cell.type), set = "stallion"), label = FALSE)

DimPlot(cor, reduction = 'sct.dsb_wnn_umap', group.by = 'cell.type',label.size = 4,
        cols = paletteDiscrete(unique(cor$cell.type), set = "stallion"), label = FALSE)
```

```{r}
DefaultAssay(cor) <- 'SCT'
Idents(cor) <- "cell.type"
rna.rnamarkers <- FindAllMarkers(cor, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.25)
write.csv(rna.rnamarkers, file ="./DE_SCT_cell.type.csv", quote = FALSE)
```

```{r}
DefaultAssay(cor) <- 'ADT'
Idents(cor) <- "cell.type"
rna.rnamarkers <- FindAllMarkers(cor, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.25)
write.csv(rna.rnamarkers, file ="./DE_ADT_cell.type.csv", quote = FALSE)
```

# Marker Gene
# GEX
```{r}
genes <- c("MYH11","CCL19","FBLN1","PTGDS","VWF","C1QA","GZMB","KIT","CD79A","JCHAIN","CD3E","MKI67","CCL21","NRXN1")
```

```{r}
DoHeatmap(cor, features = genes, assay = "SCT", group.colors = paletteDiscrete(unique(cor$cell.type), set = "stallion"), size = 2, angle = 90) + NoLegend() + scale_fill_gradientn(colours=paletteContinuous("solarExtra"))

ggsave(filename="heatmap_GEX.png")
```

# ADT
```{r}
adts <- c("ITGB1.1","FAP.1","THY1.1","MME.1","PECAM1.1","CSF2RA.1","IL3RA.1","KIT.1","CD19.1","CD27.1","CD3D.1","CD2.1","MRC1.1","NCAM1.1")
```

```{r}
DoHeatmap(cor, features = adts, assay = "ADT", group.colors = paletteDiscrete(unique(cor$cell.type), set = "stallion"), size = 2, angle = 90) + NoLegend() + scale_fill_gradientn(colours=paletteContinuous("blueYellow"))

ggsave(filename="heatmap_ADT.png")
```

```{r}
DefaultAssay(cor) <- "SCT"
plot_density(cor, features = "ITGA9", reduction = 'rna.umap')
```

# Add relevant meta-data
```{r}
fun <- function(x) {
  if (x == "sample51") {26} 
  else if (x == "sample50") {67}
  else if (x == "sample48") {48}
  else if (x == "sample47") {63}
  else if (x == "sample46") {66}
  else if (x == "sample44") {48}
  else if (x == "sample43") {44}
  else if (x == "sample40") {62}
  else if (x == "sample38") {65}
  else if (x == "sample37") {63}
  else if (x == "sample36") {68}
  else if (x == "sample35") {54}
  else if (x == "sample31") {38}
  else if (x == "sample25") {53}
  else if (x == "sample24") {64}
  else if (x == "sample23") {45}
  else if (x == "sample22") {59}
  else if (x == "sample21") {64}
  else if (x == "sample26") {41}
  else if (x == "sample20") {48}
  else if (x == "sample19") {62}
  else if (x == "sample18") {58}
  else if (x == "sample14") {52}
  else if (x == "sample16") {59}
  else if (x == "sample11") {47}
  else if (x == "sample10") {65}
  else if (x == "WashU2") {49}
  else if (x == "WashU1") {57}
}
cor$Age <- mapply(fun, cor$sampleID)
```

```{r}
fun <- function(x) {
  if (x == "sample51") {"M"} 
  else if (x == "sample50") {"M"}
  else if (x == "sample48") {"M"}
  else if (x == "sample47") {"M"}
  else if (x == "sample46") {"M"}
  else if (x == "sample44") {"F"}
  else if (x == "sample43") {"M"}
  else if (x == "sample40") {"M"}
  else if (x == "sample38") {"F"}
  else if (x == "sample37") {"M"}
  else if (x == "sample36") {"F"}
  else if (x == "sample35") {"F"}
  else if (x == "sample31") {"F"}
  else if (x == "sample25") {"M"}
  else if (x == "sample24") {"F"}
  else if (x == "sample23") {"M"}
  else if (x == "sample22") {"M"}
  else if (x == "sample21") {"M"}
  else if (x == "sample26") {"F"}
  else if (x == "sample20") {"M"}
  else if (x == "sample19") {"M"}
  else if (x == "sample18") {"M"}
  else if (x == "sample14") {"M"}
  else if (x == "sample16") {"M"}
  else if (x == "sample11") {"M"}
  else if (x == "sample10") {"F"}
  else if (x == "WashU2") {"M"}
  else if (x == "WashU1") {"M"}
}
cor$Sex <- mapply(fun, cor$sampleID)
```

```{r}
fun <- function(x) {
  if (x == "sample51") {"White"} 
  else if (x == "sample50") {"White"}
  else if (x == "sample48") {"White"}
  else if (x == "sample47") {"White"}
  else if (x == "sample46") {"White"}
  else if (x == "sample44") {"White"}
  else if (x == "sample43") {"White"}
  else if (x == "sample40") {"AA"}
  else if (x == "sample38") {"White"}
  else if (x == "sample37") {"White"}
  else if (x == "sample36") {"AA"}
  else if (x == "sample35") {"AA"}
  else if (x == "sample31") {"White"}
  else if (x == "sample25") {"AA"}
  else if (x == "sample24") {"White"}
  else if (x == "sample23") {"White"}
  else if (x == "sample22") {"White"}
  else if (x == "sample21") {"White"}
  else if (x == "sample26") {"White"}
  else if (x == "sample20") {"White"}
  else if (x == "sample19") {"AA"}
  else if (x == "sample18") {"AA"}
  else if (x == "sample14") {"White"}
  else if (x == "sample16") {"White"}
  else if (x == "sample11") {"White"}
  else if (x == "sample10") {"White"}
  else if (x == "WashU2") {"Asian"}
  else if (x == "WashU1") {"AA"}
}
cor$Race <- mapply(fun, cor$sampleID)
```

```{r}
fun <- function(x) {
  if (x == "sample51") {"NICM"} 
  else if (x == "sample50") {"ICM"}
  else if (x == "sample48") {"ICM"}
  else if (x == "sample47") {"ICM"}
  else if (x == "sample46") {"ICM"}
  else if (x == "sample44") {"NICM"}
  else if (x == "sample43") {"Donor"}
  else if (x == "sample40") {"Donor"}
  else if (x == "sample38") {"Donor"}
  else if (x == "sample37") {"ICM"}
  else if (x == "sample36") {"NICM"}
  else if (x == "sample35") {"Donor"}
  else if (x == "sample31") {"Donor"}
  else if (x == "sample25") {"NICM"}
  else if (x == "sample24") {"NICM"}
  else if (x == "sample23") {"NICM"}
  else if (x == "sample22") {"NICM"}
  else if (x == "sample21") {"NICM"}
  else if (x == "sample26") {"Donor"}
  else if (x == "sample20") {"ICM"}
  else if (x == "sample19") {"ICM"}
  else if (x == "sample18") {"ICM"}
  else if (x == "sample14") {"NICM"}
  else if (x == "sample16") {"ICM"}
  else if (x == "sample11") {"ICM"}
  else if (x == "sample10") {"NICM"}
  else if (x == "WashU2") {"ICM"}
  else if (x == "WashU1") {"NICM"}
}
cor$HF <- mapply(fun, cor$sampleID)
```

```{r}
fun <- function(x) {
  if (x == "sample51") {"0"} 
  else if (x == "sample50") {"1"}
  else if (x == "sample48") {"1"}
  else if (x == "sample47") {"1"}
  else if (x == "sample46") {"1"}
  else if (x == "sample44") {"1"}
  else if (x == "sample43") {"0"}
  else if (x == "sample40") {"0"}
  else if (x == "sample38") {"1"}
  else if (x == "sample37") {"1"}
  else if (x == "sample36") {"1"}
  else if (x == "sample35") {"0"}
  else if (x == "sample31") {"0"}
  else if (x == "sample25") {"0"}
  else if (x == "sample24") {"0"}
  else if (x == "sample23") {"0"}
  else if (x == "sample22") {"1"}
  else if (x == "sample21") {"0"}
  else if (x == "sample26") {"1"}
  else if (x == "sample20") {"1"}
  else if (x == "sample19") {"1"}
  else if (x == "sample18") {"1"}
  else if (x == "sample14") {"0"}
  else if (x == "sample16") {"1"}
  else if (x == "sample11") {"1"}
  else if (x == "sample10") {"1"}
  else if (x == "WashU2") {"1"}
  else if (x == "WashU1") {"0"}
}
cor$Disease <- mapply(fun, cor$sampleID)
```

```{r}
fun <- function(x) {
  if (x == "sample51") {"0"} 
  else if (x == "sample50") {"1"}
  else if (x == "sample48") {"1"}
  else if (x == "sample47") {"1"}
  else if (x == "sample46") {"1"}
  else if (x == "sample44") {"0"}
  else if (x == "sample43") {"0"}
  else if (x == "sample40") {"0"}
  else if (x == "sample38") {"0"}
  else if (x == "sample37") {"0"}
  else if (x == "sample36") {"0"}
  else if (x == "sample35") {"0"}
  else if (x == "sample31") {"0"}
  else if (x == "sample25") {"0"}
  else if (x == "sample24") {"0"}
  else if (x == "sample23") {"0"}
  else if (x == "sample22") {"0"}
  else if (x == "sample21") {"0"}
  else if (x == "sample26") {"1"}
  else if (x == "sample20") {"0"}
  else if (x == "sample19") {"0"}
  else if (x == "sample18") {"1"}
  else if (x == "sample14") {"0"}
  else if (x == "sample16") {"1"}
  else if (x == "sample11") {"1"}
  else if (x == "sample10") {"0"}
  else if (x == "WashU2") {"0"}
  else if (x == "WashU1") {"0"}
}
cor$Stent <- mapply(fun, cor$sampleID)
```

```{r}
fun <- function(x) {
  if (x == "sample50") {"61-70"}
  else if (x == "sample48") {"35-50"}
  else if (x == "sample47") {"61-70"}
  else if (x == "sample46") {"61-70"}
  else if (x == "sample44") {"35-50"}
  else if (x == "sample43") {"35-50"}
  else if (x == "sample40") {"61-70"}
  else if (x == "sample38") {"61-70"}
  else if (x == "sample37") {"61-70"}
  else if (x == "sample36") {"61-70"}
  else if (x == "sample35") {"51-60"}
  else if (x == "sample31") {"35-50"}
  else if (x == "sample25") {"51-60"}
  else if (x == "sample24") {"61-70"}
  else if (x == "sample23") {"35-50"}
  else if (x == "sample22") {"51-60"}
  else if (x == "sample21") {"61-70"}
  else if (x == "sample26") {"35-50"}
  else if (x == "sample20") {"35-50"}
  else if (x == "sample19") {"61-70"}
  else if (x == "sample18") {"51-60"}
  else if (x == "sample14") {"51-60"}
  else if (x == "sample16") {"51-60"}
  else if (x == "sample11") {"35-50"}
  else if (x == "sample10") {"61-70"}
  else if (x == "WashU2") {"35-50"}
  else if (x == "WashU1") {"51-60"}
}
cor$AgeRange <- mapply(fun, cor$sampleID)
```

```{r}
ggplot(cor@meta.data, aes(x=sampleID, fill=cell.type)) + geom_bar(position = "fill") + theme_linedraw() + theme(axis.text.x = element_text(angle = 90)) +  scale_fill_manual(values=as.vector(paletteDiscrete(unique(cor$cell.type), set = "stallion"))) + theme(axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank()) 
```

```{r}
ggplot(cor@meta.data, aes(x=AgeRange, fill=cell.type)) + geom_bar(position = "fill") + theme_linedraw() + theme(axis.text.x = element_text(angle = 90)) +  scale_fill_manual(values=as.vector(paletteDiscrete(unique(cor$cell.type), set = "stallion"))) + theme(axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank()) 
```

```{r}
ggplot(cor@meta.data, aes(x=Disease, fill=cell.type)) + geom_bar(position = "fill") + theme_linedraw() + theme(axis.text.x = element_text(angle = 90)) +  scale_fill_manual(values=as.vector(paletteDiscrete(unique(cor$cell.type), set = "stallion"))) + theme(axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank()) 
```

```{r}
ggplot(cor@meta.data, aes(x=Stent, fill=cell.type)) + geom_bar(position = "fill") + theme_linedraw() + theme(axis.text.x = element_text(angle = 90)) +  scale_fill_manual(values=as.vector(paletteDiscrete(unique(cor$cell.type), set = "stallion"))) + theme(axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank()) 
```

```{r}
ggplot(cor@meta.data, aes(x=HF, fill=cell.type)) + geom_bar(position = "fill") + theme_linedraw() + theme(axis.text.x = element_text(angle = 90)) +  scale_fill_manual(values=as.vector(paletteDiscrete(unique(cor$cell.type), set = "stallion"))) + theme(axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank()) 
```
```{r}
ggplot(cor@meta.data, aes(x=Sex, fill=cell.type)) + geom_bar(position = "fill") + theme_linedraw() + theme(axis.text.x = element_text(angle = 90)) +  scale_fill_manual(values=as.vector(paletteDiscrete(unique(cor$cell.type), set = "stallion"))) + theme(axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank()) 
```
```{r}
library("scProportionTest")
prop_test <- sc_utils(cor)
```

```{r}
prop_test <- permutation_test(
	prop_test, cluster_identity = "cell.type",
	sample_1 = "F", sample_2 = "M",
	sample_identity = "Sex"
)
```

```{r}
permutation_plot(prop_test)
```


```{r}
cor <- readRDS("./integrated_annotated.rds")
```

```{r}
DefaultAssay(cor) <- "SCT"
FeaturePlot(cor, features = "IGFBP7", reduction = "rna.umap")
```
```{r}
VlnPlot(cor, features = "IGFBP7", group.by = "cell.type", pt.size = 0)
```


# CLint Miller bulk coronary plaques
```{r}
DefaultAssay(cor) <- "SCT"
genes <- c("FGF13","LPIN1","KYNU","CXCL12","C1QA","CD14","CD73","APOE","NOS1","SOD2","VDR","SLC35E3","ATXN3","MYH11","MYH10","ACTA2")
genes_exp <- AverageExpression(cor, features = genes, group.by = "Stent")
```

# Senescence Genes
```{r}
DefaultAssay(cor) <- "SCT"
sen_genes <- c("ACVR1B","ANG","ANGPT1","ANGPTL4","AREG","AXL","BEX3","BMP2","BMP6","C3","CCL1","CCL13","CCL16","CCL2","CCL20","CCL24","CCL26","CCL3","CCL3L1","CCL4","CCL5","CCL7","CCL8","CD55","CD9","CSF1","CSF2","CSF2RB","CST4","CTNNB1","CTSB","CXCL1","CXCL10","CXCL12","CXCL16","CXCL2","CXCL3","CXCL8","CXCR2","DKK1","EDN1","EGF","EGFR","EREG","ESM1","ETS2","FAS","FGF1","FGF2","FGF7","GDF15","GEM","GMFG","HGF","HMGB1","ICAM1","ICAM3","IGF1","IGFBP1","IGFBP2","IGFBP3","IGFBP4","IGFBP5","IGFBP6","IGFBP7","IL10","IL13","IL15","IL18","IL1A","IL1B","IL2","IL32","IL6","IL6ST","IL7","INHA","IQGAP2","ITGA2","ITPKA","JUN","KITLG","LCP1","MIF","MMP1","MMP10","MMP12","MMP13","MMP14","MMP2","MMP3","MMP9","NAP1L4","NRG1","PAPPA","PECAM1","PGF","PIGF","PLAT","PLAU","PLAUR","PTBP1","PTGER2","PTGES","RPS6KA5","SCAMP4","SELPLG","SEMA3F","SERPINB4","SERPINE1","SERPINE2","SPP1","SPX","TIMP2","TNF","TNFRSF10C","TNFRSF11B","TNFRSF1A","TNFRSF1B","TUBGCP2","VEGFA","VEGFC","VGF","WNT16","WNT2")
genes_exp <- AverageExpression(cor, features = sen_genes, group.by = "cell.type")
```

```{r}
pheatmap(genes_exp$SCT, scale = "row", border_color = NA, col=paletteContinuous("solarExtra"), cluster_rows = TRUE, cluster_cols = TRUE)
```

# Export h5ad file for scanpy processing
```{r}
cor$cell.type <- as.character(cor$cell.type) 
slot(cor$SCT@SCTModel.list[[1]], 'median_umi') = median(cor$SCT@SCTModel.list[[1]]@cell.attributes$umi)
```

```{r}
SaveH5Seurat(cor, filename = "./annotated.h5Seurat")
```

```{r}
Convert("./annotated.h5Seurat", dest = "h5ad")
```

# Export h5ad file for tangram
```{r}
DefaultAssay(cor) <- "RNA"
cor@assays[["SCT"]] <- NULL
cor@assays[["ADT"]] <- NULL
```

```{r}
SaveH5Seurat(cor, filename = "./annotated_raw.h5Seurat")
```

```{r}
Convert("./annotated_raw.h5Seurat", dest = "h5ad")
```

```{r}
write.csv(cor@meta.data, file = "./meta_raw.csv", quote = TRUE)
```

```{r}
table(cor$sampleID, cor$Stent)
```

```{r}
prop.table(table(Idents(cor), cor$sampleID), margin = 2)
```

```{r}
library("scProportionTest")
prop_test <- sc_utils(cor)
```

```{r}
prop_test <- permutation_test(
	prop_test, cluster_identity = "cell.type",
	sample_1 = "0", sample_2 = "1",
	sample_identity = "Stent"
)
```

```{r}
permutation_plot(prop_test)
```


```{r}
DefaultAssay(cor) <- "SCT"
FeaturePlot(cor, reduction = 'rna.umap', features = "RUNX1", raster=FALSE) + scale_color_gradientn(colors=paletteContinuous("solarExtra"), oob=scales::squish, limits=c(0,1)) 
```

```{r}
DotPlot(cor, features = c("RUNX1","SIPA1","SREBF1","TOM1L2","UNC13D","SAP30"), group.by = "cell.type") + RotatedAxis()
```

```{r}
cor <- readRDS("integrated_annotated.rds")
```

```{r}
pdf("./panels/cell_comp_sample.pdf", useDingbats = FALSE, width=4.3, height=3)
ggplot(cor@meta.data, aes(x=sampleID, fill=cell.type)) + geom_bar(position = "fill") + theme_linedraw() + theme(axis.text.x = element_text(angle = 90)) +  scale_fill_manual(values=as.vector(paletteDiscrete(unique(cor$cell.type), set = "stallion"))) + theme(axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank()) 
dev.off()
```

```{r}
pdf("./panels/nFeature_ADT_sample.pdf", useDingbats = FALSE, width=4.3, height=3)
VlnPlot(cor, features = "nFeature_ADT", group.by = "sampleID", pt.size = 0) + NoLegend()
dev.off()
```
```{r}
DefaultAssay(cor) <- "SCT"
FeaturePlot(cor, reduction = 'rna.umap', features = "scrublet_score", raster=FALSE) + scale_color_gradientn(colors=paletteContinuous("solarExtra"), oob=scales::squish, limits=c(0,1)) 
```

#######
```{r}
library(Seurat)
library(ggplot2)
library(cowplot)
```

```{r}
cor <- readRDS("./integrated_annotated.rds")
```

```{r}
check_integration_efficient <- function(seurat_obj) {
  # Extract only necessary data
  dims <- seurat_obj[["rna.umap"]]@cell.embeddings[,1:2]
  samples <- seurat_obj$sampleID
  
  # Calculate sample stats
  sample_counts <- table(samples)
  print(sample_counts)
  
  # Calculate mixing score (simplified metric)
  k <- 30  # number of neighbors
  mixing_score <- mean(sapply(1:nrow(dims), function(i) {
    dists <- colSums((t(dims) - dims[i,])^2)
    nearest <- order(dists)[2:(k+1)]
    sum(samples[nearest] != samples[i]) / k
  }))
  
  cat("Mixing score:", round(mixing_score, 3), "\n")
  
  # Clean up
  rm(dims)
  gc()

}
```

```{r}
check_integration_efficient(cor)
```

```{r}
cor <- readRDS("integrated_annotated.rds")
```

```{r}
DefaultAssay(cor) <- "SCT"
VlnPlot(cor, features = "NPR3", group.by = "cell.type", pt.size = 0)
```





















